# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FanNetWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FanNetWork

  target 'FanNetWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FanNetWorkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
